server:
  port: ${SPRING_SERVER_PORT}

kafka:
  topics:
    commands: commands
    queries: queries
    responses: responses
    events: events

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: chat-consumers
      auto-offset-reset: earliest
  data:
    mongodb:
      database: ${MONGO_DATABASE_NAME}
      uri: ${MONGO_DATABASE_URI}

handler:
  commands:
    users:
      kafka:
        topic: users.commands
      rabbit:
        exchange: users.commands
      pubsub:
        subscription: users.commands
  queries:
    users:
      kafka:
        topic: users.queries
      rabbit:
        exchange: users.queries
      pubsub:
        subscription: users.queries
  shared:
    kafka:
      consumer-group-id: chatogt

bus:
  events:
    users:
      kafka:
        topic: users.commands
      rabbit:
        exchange: users.commands
      pubsub:
        subscription: users.commands
