server:
  port: ${SPRING_SERVER_PORT}

spring:
  config:
    import: "classpath:shared.yaml"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: chatogt-user-management
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  data:
    mongodb:
      database: ${MONGO_DATABASE_NAME}
      uri: ${MONGO_DATABASE_URI}

handler:
  commands:
    users:
      kafka:
        topic: users.commands
      rabbit:
        exchange: users.commands
      pubsub:
        subscription: users.commands
  queries:
    users:
      kafka:
        topic: users.queries
      rabbit:
        exchange: users.queries
      pubsub:
        subscription: users.queries
