server:
  port: ${SPRING_SERVER_PORT}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: "chatogt"

grpc:
  server:
    port: ${GRPC_SERVER_PORT}
    reflection-service-enabled: true

bus:
  commands:
    users:
      kafka:
        topic: users.commands
      rabbit:
        exchange: users.commands
      pubsub:
        subscription: users.commands
  queries:
    users:
      kafka:
        topic: users.queries
      rabbit:
        exchange: users.queries
      pubsub:
        subscription: users.queries
  responses:
    users:
      kafka:
        topic: users.responses
      rabbit:
        exchange: users.responses
      pubsub:
        subscription: users.responses
